version: "3.11"

services:
  web:
    build: ./djangokurs.online
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangokurs.online/:/usr/src/djangokurs.online/
    ports:
      - 8000:8000
    env_file: 
      - ./blog/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=djangokurs_adminuser
      - POSTGRES_PASSWORD=Sifra123!
      - POSTGRES_DB=djangokurs

volumes:
  postgres_data:
   
   
   #container_name: django_kurs
   #command: gunicorn blog.wsgi:application --bind 0.0.0.0:8001
