version: "3.11"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/djangokurs.online/web/staticfiles
    expose:
      - 8000
    # volumes: 
    #   - ./django
    ports:
      - 8000:8000
    env_file: 
      - ./blog/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./blog/.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/djangokurs.online/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: 
   
   #container_name: django_kurs

