version: "3.11"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/djangokurs.online/web/staticfiles
    expose:
      - 8000
    env_file: 
      - ./blog/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./blog/.env
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/djangokurs.online/web/staticfiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./blog/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d    
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    
volumes:
  postgres_data:
  static_volume: 
  certs:
  html:
  vhost:
  acme: 
   #container_name: django_kurs

